/*CREACION DE LA BASE DE DATOS DEL PROYECTO SOLUTION FOR ASSISTANCE SFA*/
CREATE DATABASE SFA;

/*ESPESIFICAR LA BASE DE DATOS QUE VAMOS A TRABAJAR*/
USE SFA;

/*CREACION DE LA TABLA USUARIO*/
CREATE TABLE usuario
(
COD_USUARIO INT NOT NULL PRIMARY KEY,
CARGO VARCHAR(30)NOT NULL,
NOMBRES VARCHAR(30)NOT NULL,
APELLIDOS VARCHAR(30)NOT NULL,
GENERO VARCHAR (30)NOT NULL,
FECHA_DE_NACIMIENTO DATE NOT NULL,
NACIONALIDAD VARCHAR(30)NOT NULL,
TIPO_DE_DOCUMENTO VARCHAR(30),
NUMERO_DE_DOCUMENTO VARCHAR(30),
DIRECCION VARCHAR(50)NOT NULL,
CORREO VARCHAR(50)NOT NULL,
TELEFONO VARCHAR(50)NOT NULL
);

/*CREACION TABLA ADMINISTADOR*/
CREATE TABLE administrador
(
COD_ADMINISTRADOR INT NOT NULL PRIMARY KEY,
COD_ASISTENCIA VARCHAR (30) NOT NULL,
COD_USUARIO VARCHAR (30) NOT NULL,
NOMBRES VARCHAR(30)NOT NULL,
APELLIDOS VARCHAR(30)NOT NULL
);

/*CREACION DE LA TABLA APRENDIZ*/
CREATE TABLE aprendiz
(
COD_APRENDIZ INT NOT NULL PRIMARY KEY,
COD_ASISTENCIA VARCHAR (30) NOT NULL,
COD_USUARIO VARCHAR (30) NOT NULL,
NOMBRES VARCHAR(30)NOT NULL,
APELLIDOS VARCHAR(30)NOT NULL,
GENERO CHAR(1)NOT NULL,
FECHA_DE_NACIMIENTO DATE NOT NULL,
NACIONALIDAD VARCHAR(30),
TIPO_DE_DOCUMENTO VARCHAR(30)NOT NULL,
NUMERO_DE_DOCUMENTO VARCHAR(30)NOT NULL,
DIRECCION VARCHAR(50)NOT NULL
);

/*CREACION DE LA TABLA FORMACION EDUCATIVA*/
CREATE TABLE formacion_educatica
(
COD_FORMACION_EDUCATIVA INT NOT NULL PRIMARY KEY,
COD_APRENDIZ VARCHAR (30) NOT NULL,
TITULO VARCHAR(30)NOT NULL,
INSTITUCION VARCHAR(50)NOT NULL
);

/*CREACION DE TABLA SEDES*/
CREATE TABLE sedes
(
COD_SEDE INT NOT NULL PRIMARY KEY,
COD_APRENDIZ VARCHAR (30) NOT NULL,
DIRECCION_SEDE VARCHAR(50)NOT NULL,
CIUDAD VARCHAR(30)NOT NULL
);

/*CREACION DE TABLA NOVEDADES*/
CREATE TABLE novedades
(
COD_NOVEDADES INT NOT NULL PRIMARY KEY,
COD_APRENDIZ VARCHAR (30) NOT NULL,
TIPO_DE_NOVEDADES VARCHAR(50)
);

/*CREACION TABLA TIPOS DE NOVEDADES*/
CREATE TABLE tipo_de_novedades
(
COD_TIPOS_DE_NOVEDADES INT NOT NULL PRIMARY KEY,
COD_APRENDIZ VARCHAR (30) NOT NULL,
COD_BUZON_DE_SUGERENCIAS VARCHAR(30)NOT NULL,
SUGERENCIA VARCHAR(100)NOT NULL,
COD_INASISTENCIAS_JUSTIFICADAS VARCHAR(30)NOT NULL,
ADJUNTAR_EVIDENCIA VARCHAR(100)NOT NULL,
COD_IMPUNTUALIDADES_CON_REPORTE VARCHAR(30)NOT NULL,
CARGAR_EVIDENCIA VARCHAR(100)
);

/*CREACION TABLA ASISTENCIA*/
CREATE TABLE asistencia
(
COD_ASISTENCIA INT NOT NULL PRIMARY KEY,
COD_NOMBRE_USUARIO VARCHAR (30) NOT NULL,
NOMBRE_DE_USUARIO VARCHAR(30),
TOMA_DE_ASISTENCIA VARCHAR(30)NOT NULL,
USUARIO VARCHAR(30)NOT NULL
);

/*CREACION TABLA SESION*/
CREATE TABLE sesion
(
COD_SESION INT NOT NULL PRIMARY KEY,
COD_ASISTENCIA INT NOT NULL,
USUARIO VARCHAR(50)NOT NULL,
CONTRASEÑA VARCHAR(30)NOT NULL
);

/*CREACION TABLA HORARIO*/
CREATE TABLE horario
(
COD_HORARIO INT NOT NULL PRIMARY KEY,
COD_ASISTENCIA VARCHAR (30) NOT NULL,
FECHA DATE NOT NULL,
HORA_INICIO DATETIME NOT NULL,
HORA_TERMINACION DATETIME NOT NULL
);

/*CREACION TABLA MODALIDAD DE ASISTENCIA*/
CREATE TABLE modalidades_de_asistencia
(
COD_MODALIDAD_DE_ASISTENCIA INT NOT NULL PRIMARY KEY,
COD_ASISTENCIA VARCHAR (30) NOT NULL,
MODALIDAD_PRESENCIAL CHAR(1)NOT NULL,
MODALIDAD_VIRTUAL CHAR(1)NOT NULL
);

/*CREACION TABLA PROGRAMAS DE FORMACION*/
CREATE TABLE programas_de_formacion
(
COD_PROGRAMAS_DE_FORMACION INT NOT NULL PRIMARY KEY,
COD_ASISTENCIA VARCHAR (30) NOT NULL,
FICHA VARCHAR(30)NOT NULL,
HORA_PROGRAMADA DATETIME NOT NULL,
DESCRIPCION_DEL_PROGRAMA VARCHAR(100)
);

/*CREACION TABLA INSTRUCTORES*/
CREATE TABLE instructores
(
COD_INSTRUCTOR INT NOT NULL PRIMARY KEY,
COD_ASISTENCIA VARCHAR (30)NOT NULL,
COD_USUARIO VARCHAR (30) NOT NULL,
NOMBRES VARCHAR(30)NOT NULL,
APELLIDOS VARCHAR(30)NOT NULL,
EMAIL VARCHAR(50)NOT NULL,
TELEFONO VARCHAR(50)NOT NULL
);

/*CREACION TABLA CARGO*/
CREATE TABLE cargo
(
COD_CARGO INT NOT NULL PRIMARY KEY,
COD_INSTRUCTORES VARCHAR (30) NOT NULL,
TITULO VARCHAR(30)NOT NULL,
INSTITUCION VARCHAR(30)NOT NULL
);

/*CREACION TABLA AREA*/
CREATE TABLE area
(
COD_AREA INT NOT NULL PRIMARY KEY,
COD_INSTRUCTORES VARCHAR (30) NOT NULL,
NOMBRE_DEL_AREA VARCHAR(30)NOT NULL,
CORREO_ELECTRONICO VARCHAR(50)NOT NULL
);

/*CREACION TABLA GESTION DE FICHAS*/
CREATE TABLE gestion_de_fichas
(
COD_GESTION_DE_FICHAS INT NOT NULL PRIMARY KEY,
COD_INSTRUCTORES VARCHAR (30) NOT NULL,
NUMERO_DE_LA_FICHA VARCHAR(30)NOT NULL,
INSTRUCTOR VARCHAR(50)NOT NULL,
PROGRAMA VARCHAR(50)NOT NULL
);

/*CREACION TABLA CREAR LISTAS DE AISTENCIA*/
CREATE TABLE crear_listas_de_asistencias
(
COD_CREAR_LISTAS_DE_ASISTENCIA INT NOT NULL PRIMARY KEY,
COD_INSTRUCTOR VARCHAR (30) NOT NULL,
HORA_INICIO DATETIME NOT NULL,
CODIGO VARCHAR(30)NOT NULL,
HORA_FINAL DATETIME NOT NULL,
FORMULARIO_FIRMAR_ASISTENCIA VARCHAR(100)
);

/*CREACION TABLA CORREO*/
CREATE TABLE correo
(
COD_CORREO INT NOT NULL PRIMARY KEY,
COD_USUARIO VARCHAR (30) NOT NULL,
CORREO VARCHAR(50)NOT NULL,
CORREO_SENA Varchar (50) NOT NULL
);

/*CREACION TABLA TELEFONO*/
CREATE TABLE telefono
(
COD_TELEFONO INT NOT NULL PRIMARY KEY,
COD_USUARIO VARCHAR (30) NOT NULL,
NUMERO VARCHAR(50)NOT NULL
);

/*CREACION LISTA INTELIGENTES*/
CREATE TABLE lista_inteligente
(
Academicas VARCHAR (50) NOT NULL,
Coorporativo VARCHAR (50) NOT NULL,
Estandar VARCHAR (50) NOT NULL
);






 





