/*INSERTAR DATOS A LA TABLA ADMINISTRADOR*/
USE sfa;
INSERT INTO administrador(COD_ADMINISTRADOR,COD_ASISTENCIA,
COD_USUARIO,NOMBRES,APELLIDOS)VALUES
('1','12','1','PABLO NICOLAS','RUIZ RODRIGUEZ');
SELECT * FROM sfa.administrador